project:
  type: website

website:
  title: "MIKE+Py"
  page-footer: "Â© 2025 DHI Group"
  favicon: dhi.ico
  site-url: https://dhi.github.io/mikepluspy
  repo-url: https://github.com/DHI/mikepluspy
  repo-actions: [edit]
  repo-subdir: docs
  page-navigation: true
  #bread-crumbs: false

  navbar:
    tools:
    - icon: github
      menu:
      - text: Source Code
        url:  https://github.com/DHI/mikepluspy
      - text: Report a Bug
        url:  https://github.com/DHI/mikepluspy/issues
    left:
      - text: "Home"
        href: index.qmd
      - text: "User Guide"
        href: user-guide/index.qmd
      # - text: "Examples"
      #   href: examples/index.qmd
      - text: "API Reference"
        href: api/index.qmd

  sidebar:
    - title: "User Guide"
      style: "docked"
      contents:
        - user-guide/index.qmd
        - user-guide/getting-started.qmd
        - user-guide/database.qmd
        - user-guide/tables.qmd
        - user-guide/queries.qmd
        - user-guide/scenarios.qmd
        - user-guide/simulations.qmd
        - user-guide/tools.qmd

  
    # - title: "Examples"
    #   style: "docked"
    #   contents:
    #     - examples/index.qmd

filters:
  - interlinks
interlinks:
  sources:
      numpy: 
        url: https://numpy.org/doc/stable/
      xarray: 
        url: https://xarray.pydata.org/en/stable/
      pandas: 
        url: https://pandas.pydata.org/docs/
      scipy: 
        url: https://docs.scipy.org/doc/scipy/

quartodoc:
  package: mikeplus
  style: pkgdown
  title: API Reference
  dir: api
  renderer:
    style: markdown
    display_name: relative
  css: api/_styles-quartodoc.css
  #dynamic: true

  sidebar:
    title: "API Reference"
    style: docked
    contents: 
      - "{{ contents }}"

  sections:
    - title: Main
      desc: ""
      contents:
        - open
        - create
    - title: Database
      desc: ""
      contents:
        - Database
        - name: TableCollection
          package: mikeplus.tables.auto_generated
          members:
            - keys
            - values
            - items
    - title: Base Table Classes
      desc: "Base classes for all table types. See these for inherited methods available on all tables."
      package: mikeplus.tables
      contents:
        - name: BaseTable
          package: mikeplus.tables.base_table
        - name: BaseGeometryTable
          package: mikeplus.tables.base_geometry_table
        - name: BaseNodeTable
          package: mikeplus.tables.base_node_table

metadata-files:
  - api/_sidebar.yml

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 6
    css:
      - api/_styles-quartodoc.css
      - style.css
  #ipynb: 
  #  theme: cosmo
  #  toc: true

# runs code locally, not in CI
execute:
  freeze: auto